name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: QuizAppBackend

      - name: Build
        run: dotnet build --no-restore
        working-directory: QuizAppBackend

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: QuizAppBackend
